# Generated by Django 3.2.9 on 2021-12-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summery',
            field=models.CharField(default='this is true', max_length=50),
        ),
    ]
